### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by ARRARIAKU2** [erikycd/Heart_segmentation#1]
Hi, thanks for sharing.

Where can I get it and how to implement it into the code?

Thank you.

Best.

**Comment by erikycd** [comment]
Hi there,

I've recently uploaded the [dataset](https://github.com/erikycd/Heart_segmentation/blob/main/MRI_dataset.rar) used in this sample code.

It contains 3 folders for: MRI images, left ventricle masks and right ventricle masks.
Just replace in code the location of those folders once you've downloaded it.

Regards,
